### ISSUE TITLE
If the gradient isn't in the same dimension as p there should be a problem.

### ISSUE THREAD

**Issue by Wenhan-Jiang** [IST-DASLab/ISTA-DASLab-Optimizers#1]
is:issue is:open         ##### STEP 12:          grad = grad.view_as(p)         p.mul_(1 - lr * wd).add_(grad, alpha=-lr)

**Comment by ionutmodo** [comment]
Hi, thank you for pointing this out. Can you please mention whether this line raised a runtime error in your setup? Note that the variable `grad` is initialized with a view of `p.grad`. When we update the parameters `p`, we use `p.grad`, which essentially has the same shape as `p` and should not raise any issue. We will add some comments to the code to make it more readable.

**Comment by Wenhan-Jiang** [comment]
File "D:\MicroAdam\Optimizers\ista_daslab_optimizers\micro_adam\micro_adam.py", line 239, in update_step
    p.mul_(1 - lr * wd).add_(grad, alpha=-lr)
RuntimeError: The size of tensor a (7) must match the size of tensor b (9408) at non-singleton dimension 3

**Comment by ionutmodo** [comment]
It seems like you modified that line of code. I have just looked at the history of `micro_adam.py` file and it has always been `        p.mul_(1 - lr * wd).add_(p.grad, alpha=-lr)`. Note that you are using `grad`, which is one dimensional, while we are using `p.grad`, that has the same shape as `p`. Please undo that change. We have never had the line `grad = grad.view_as(p)` in our code.

**Comment by Wenhan-Jiang** [comment]
Thank you.
